# Generated by Django 4.0 on 2022-01-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccms_site', '0003_book_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='title2',
            new_name='title',
        ),
    ]
