# Generated by Django 4.0 on 2022-01-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccms_site', '0004_rename_title2_home_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
