# Generated by Django 4.0 on 2022-01-24 19:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms_site', '0005_remove_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('bodytext', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.DeleteModel(
            name='home',
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
