# Generated by Django 3.2.12 on 2022-03-02 11:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms_site', '0007_delete_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupage',
            options={'verbose_name': 'Strona menu', 'verbose_name_plural': 'Strony menu'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name': 'Wpis aktualności', 'verbose_name_plural': 'Wpisy aktualności'},
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/', verbose_name='miniaturka'),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='bodytext',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='pole tekstowe'),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='pole tekstowe'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish', verbose_name='skrót'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='szkic', max_length=14),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Tytuł'),
        ),
    ]
